#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Track-Log
version:      0.01
version_from: lib/Geo/Track/Log.pm
installdirs:  site
requires:
    XML::Simple:                   2.12
    Time::Piece:                   1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
